/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSearchRouteImport } from './routes/_shell.search'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellPostRouteImport } from './routes/_shell.post'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellMessagesRouteImport } from './routes/_shell.messages'
import { Route as ShellHomeRouteImport } from './routes/_shell.home'
import { Route as ShellFavoritesRouteImport } from './routes/_shell.favorites'
import { Route as ShellMessagesIndexRouteImport } from './routes/_shell.messages.index'
import { Route as ShellUserUsernameRouteImport } from './routes/_shell.user.$username'
import { Route as ShellMessagesMessageIdRouteImport } from './routes/_shell.messages.$messageId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPostRoute = ShellPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMessagesRoute = ShellMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeRoute = ShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFavoritesRoute = ShellFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMessagesIndexRoute = ShellMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellMessagesRoute,
} as any)
const ShellUserUsernameRoute = ShellUserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMessagesMessageIdRoute = ShellMessagesMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => ShellMessagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/favorites': typeof ShellFavoritesRoute
  '/home': typeof ShellHomeRoute
  '/messages': typeof ShellMessagesRouteWithChildren
  '/notifications': typeof ShellNotificationsRoute
  '/post': typeof ShellPostRoute
  '/profile': typeof ShellProfileRoute
  '/search': typeof ShellSearchRoute
  '/settings': typeof ShellSettingsRoute
  '/post/$id': typeof PostIdRoute
  '/messages/$messageId': typeof ShellMessagesMessageIdRoute
  '/user/$username': typeof ShellUserUsernameRoute
  '/messages/': typeof ShellMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/favorites': typeof ShellFavoritesRoute
  '/home': typeof ShellHomeRoute
  '/notifications': typeof ShellNotificationsRoute
  '/post': typeof ShellPostRoute
  '/profile': typeof ShellProfileRoute
  '/search': typeof ShellSearchRoute
  '/settings': typeof ShellSettingsRoute
  '/post/$id': typeof PostIdRoute
  '/messages/$messageId': typeof ShellMessagesMessageIdRoute
  '/user/$username': typeof ShellUserUsernameRoute
  '/messages': typeof ShellMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/register': typeof RegisterRoute
  '/_shell/favorites': typeof ShellFavoritesRoute
  '/_shell/home': typeof ShellHomeRoute
  '/_shell/messages': typeof ShellMessagesRouteWithChildren
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/post': typeof ShellPostRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/post/$id': typeof PostIdRoute
  '/_shell/messages/$messageId': typeof ShellMessagesMessageIdRoute
  '/_shell/user/$username': typeof ShellUserUsernameRoute
  '/_shell/messages/': typeof ShellMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/favorites'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/search'
    | '/settings'
    | '/post/$id'
    | '/messages/$messageId'
    | '/user/$username'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/favorites'
    | '/home'
    | '/notifications'
    | '/post'
    | '/profile'
    | '/search'
    | '/settings'
    | '/post/$id'
    | '/messages/$messageId'
    | '/user/$username'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/register'
    | '/_shell/favorites'
    | '/_shell/home'
    | '/_shell/messages'
    | '/_shell/notifications'
    | '/_shell/post'
    | '/_shell/profile'
    | '/_shell/search'
    | '/_shell/settings'
    | '/post/$id'
    | '/_shell/messages/$messageId'
    | '/_shell/user/$username'
    | '/_shell/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  PostIdRoute: typeof PostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/post': {
      id: '/_shell/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof ShellPostRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/messages': {
      id: '/_shell/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ShellMessagesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home': {
      id: '/_shell/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ShellHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/favorites': {
      id: '/_shell/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ShellFavoritesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/messages/': {
      id: '/_shell/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof ShellMessagesIndexRouteImport
      parentRoute: typeof ShellMessagesRoute
    }
    '/_shell/user/$username': {
      id: '/_shell/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof ShellUserUsernameRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/messages/$messageId': {
      id: '/_shell/messages/$messageId'
      path: '/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof ShellMessagesMessageIdRouteImport
      parentRoute: typeof ShellMessagesRoute
    }
  }
}

interface ShellMessagesRouteChildren {
  ShellMessagesMessageIdRoute: typeof ShellMessagesMessageIdRoute
  ShellMessagesIndexRoute: typeof ShellMessagesIndexRoute
}

const ShellMessagesRouteChildren: ShellMessagesRouteChildren = {
  ShellMessagesMessageIdRoute: ShellMessagesMessageIdRoute,
  ShellMessagesIndexRoute: ShellMessagesIndexRoute,
}

const ShellMessagesRouteWithChildren = ShellMessagesRoute._addFileChildren(
  ShellMessagesRouteChildren,
)

interface ShellRouteChildren {
  ShellFavoritesRoute: typeof ShellFavoritesRoute
  ShellHomeRoute: typeof ShellHomeRoute
  ShellMessagesRoute: typeof ShellMessagesRouteWithChildren
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPostRoute: typeof ShellPostRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUserUsernameRoute: typeof ShellUserUsernameRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellFavoritesRoute: ShellFavoritesRoute,
  ShellHomeRoute: ShellHomeRoute,
  ShellMessagesRoute: ShellMessagesRouteWithChildren,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPostRoute: ShellPostRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUserUsernameRoute: ShellUserUsernameRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  RegisterRoute: RegisterRoute,
  PostIdRoute: PostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
